In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
from google.colab import files
uploaded =files.upload()

Saving Decathlon_Synthetic_Data.xlsx to Decathlon_Synthetic_Data.xlsx

In [4]:
df=pd.read_excel("Decathlon_Synthetic_Data.xlsx")

In [5]:
df.head()

,Order_ID,Order_Date,Order_Time,Customer_ID,Customer_Name,Gender,Age,Age_Group,City,State,...,Salesperson,Delivery_Type,Delivery_Days,Customer_Rating,Return_Status,Return_Reason,Promotion_Campaign,Quarter,Month,Year
0,ORD100001,2024-12-07,11:53:06,CUST9177,Rohit Mehta,Female,61,Senior,Ahmedabad,Gujarat,...,Rahul Yadav,Home Delivery,6,3,Not Returned,Not Applicable,Diwali Mega Sale,Q4,December,2024
1,ORD100002,2024-02-20,20:12:38,CUST8120,Ananya Verma,Male,32,Adult,Chandigarh,Chandigarh,...,Arjun Mehta,Home Delivery,5,2,Not Returned,Not Applicable,New Year Fitness Campaign,Q1,February,2024
2,ORD100003,2024-09-15,14:17:10,CUST5601,Arjun Singh,Male,37,Adult,Kolkata,West Bengal,...,Rahul Mehta,Home Delivery,7,5,Not Returned,Not Applicable,Back To Sports,Q3,September,2024
3,ORD100004,2026-05-09,13:02:00,CUST4035,Karan Patel,Male,20,Adult,Jaipur,Rajasthan,...,Priya Verma,Pickup,0,5,Not Returned,Not Applicable,Back To Sports,Q2,May,2026
4,ORD100005,2024-01-22,21:47:28,CUST7304,Ananya Yadav,Female,17,Teen,Bengaluru,Karnataka,...,Pooja Singh,Home Delivery,4,5,Not Returned,Not Applicable,Independence Day Offer,Q1,January,2024

In [6]:
df.tail()

,Order_ID,Order_Date,Order_Time,Customer_ID,Customer_Name,Gender,Age,Age_Group,City,State,...,Salesperson,Delivery_Type,Delivery_Days,Customer_Rating,Return_Status,Return_Reason,Promotion_Campaign,Quarter,Month,Year
29995,ORD129996,2026-01-05,12:20:47,CUST6280,Aman Jain,Female,19,Teen,Jaipur,Rajasthan,...,Rohit Gupta,Pickup,0,1,Not Returned,Not Applicable,Summer Sale,Q1,January,2026
29996,ORD129997,2026-08-31,13:20:20,CUST9479,Riya Yadav,Male,30,Adult,Hyderabad,Telangana,...,Neha Sharma,Pickup,0,3,Not Returned,Not Applicable,Republic Day Sale,Q3,August,2026
29997,ORD129998,2024-05-28,16:47:29,CUST1668,Ananya Sharma,Female,14,Teen,Noida,Uttar Pradesh,...,Neha Sharma,Home Delivery,6,1,Not Returned,Not Applicable,New Year Fitness Campaign,Q2,May,2024
29998,ORD129999,2024-10-12,16:34:06,CUST8399,Arjun Malhotra,Male,13,Teen,Gurgaon,Haryana,...,Pooja Jain,Pickup,0,5,Not Returned,Not Applicable,Independence Day Offer,Q4,October,2024
29999,ORD130000,2024-07-05,11:45:13,CUST7696,Neha Patel,Female,44,Adult,Kolkata,West Bengal,...,Ananya Verma,Home Delivery,2,1,Not Returned,Not Applicable,Diwali Mega Sale,Q3,July,2024

**Data Validation**

In [7]:
df.shape

(30000, 39)

In [8]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Time', 'Customer_ID', 'Customer_Name',
       'Gender', 'Age', 'Age_Group', 'City', 'State', 'Membership_Type',
       'Customer_Segment', 'Product_ID', 'Product_Name', 'Product_Category',
       'Brand', 'Sport_Type', 'Quantity', 'Unit_Price', 'Discount_Percent',
       'Discount_Amount', 'Sales_Amount', 'Final_Amount', 'Cost_Price',
       'Profit', 'Store_ID', 'Store_Name', 'Sales_Channel', 'Payment_Method',
       'Salesperson', 'Delivery_Type', 'Delivery_Days', 'Customer_Rating',
       'Return_Status', 'Return_Reason', 'Promotion_Campaign', 'Quarter',
       'Month', 'Year'],
      dtype='object')

In [9]:
df.dtypes

Order_ID                      object
Order_Date            datetime64[ns]
Order_Time                    object
Customer_ID                   object
Customer_Name                 object
Gender                        object
Age                            int64
Age_Group                     object
City                          object
State                         object
Membership_Type               object
Customer_Segment              object
Product_ID                    object
Product_Name                  object
Product_Category              object
Brand                         object
Sport_Type                    object
Quantity                       int64
Unit_Price                     int64
Discount_Percent               int64
Discount_Amount              float64
Sales_Amount                   int64
Final_Amount                 float64
Cost_Price                   float64
Profit                       float64
Store_ID                      object
Store_Name                    object
Sales_Channel                 object
Payment_Method                object
Salesperson                   object
Delivery_Type                 object
Delivery_Days                  int64
Customer_Rating                int64
Return_Status                 object
Return_Reason                 object
Promotion_Campaign            object
Quarter                       object
Month                         object
Year                           int64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            30000 non-null  object
 1   Order_Date          30000 non-null  datetime64[ns]
 2   Order_Time          30000 non-null  object
 3   Customer_ID         30000 non-null  object
 4   Customer_Name       30000 non-null  object
 5   Gender              30000 non-null  object
 6   Age                 30000 non-null  int64
 7   Age_Group           30000 non-null  object
 8   City                30000 non-null  object
 9   State               30000 non-null  object
 10  Membership_Type     30000 non-null  object
 11  Customer_Segment    30000 non-null  object
 12  Product_ID          30000 non-null  object
 13  Product_Name        30000 non-null  object
 14  Product_Category    30000 non-null  object
 15  Brand               30000 non-null  object
 16  Sport_Type          30000 non-null  object
 17  Quantity            30000 non-null  int64
 18  Unit_Price          30000 non-null  int64
 19  Discount_Percent    30000 non-null  int64
 20  Discount_Amount     30000 non-null  float64
 21  Sales_Amount        30000 non-null  int64
 22  Final_Amount        30000 non-null  float64
 23  Cost_Price          30000 non-null  float64
 24  Profit              30000 non-null  float64
 25  Store_ID            30000 non-null  object
 26  Store_Name          30000 non-null  object
 27  Sales_Channel       30000 non-null  object
 28  Payment_Method      30000 non-null  object
 29  Salesperson         30000 non-null  object
 30  Delivery_Type       30000 non-null  object
 31  Delivery_Days       30000 non-null  int64
 32  Customer_Rating     30000 non-null  int64
 33  Return_Status       30000 non-null  object
 34  Return_Reason       30000 non-null  object
 35  Promotion_Campaign  30000 non-null  object
 36  Quarter             30000 non-null  object
 37  Month               30000 non-null  object
 38  Year                30000 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(8), object(26)
memory usage: 8.9+ MB

In [11]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Order_Time            0
Customer_ID           0
Customer_Name         0
Gender                0
Age                   0
Age_Group             0
City                  0
State                 0
Membership_Type       0
Customer_Segment      0
Product_ID            0
Product_Name          0
Product_Category      0
Brand                 0
Sport_Type            0
Quantity              0
Unit_Price            0
Discount_Percent      0
Discount_Amount       0
Sales_Amount          0
Final_Amount          0
Cost_Price            0
Profit                0
Store_ID              0
Store_Name            0
Sales_Channel         0
Payment_Method        0
Salesperson           0
Delivery_Type         0
Delivery_Days         0
Customer_Rating       0
Return_Status         0
Return_Reason         0
Promotion_Campaign    0
Quarter               0
Month                 0
Year                  0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df["Order_ID"].duplicated().sum()

np.int64(0)

In [15]:
df.describe()

,Order_Date,Age,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Sales_Amount,Final_Amount,Cost_Price,Profit,Delivery_Days,Customer_Rating,Year
count,30000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,2025-06-01 05:22:50.880000256,41.050700,3.027533,4607.466267,12.724400,1783.340965,14019.160667,12235.819702,8478.924532,3756.895170,1.322333,2.999300,2024.932067
min,2024-01-01 00:00:00,13.000000,1.000000,100.000000,0.000000,0.000000,100.000000,62.000000,36.390000,11.040000,0.000000,1.000000,2024.000000
25%,2024-09-15 00:00:00,27.000000,2.000000,899.000000,6.000000,89.900000,2499.000000,2124.150000,1439.012500,630.897500,0.000000,2.000000,2024.000000
50%,2025-05-30 00:00:00,41.000000,3.000000,2999.000000,13.000000,749.700000,8268.500000,7245.000000,4957.330000,2129.045000,0.000000,3.000000,2025.000000
75%,2026-02-08 00:00:00,56.000000,4.000000,6569.000000,19.000000,2284.760000,18999.000000,16620.250000,11450.660000,4911.890000,2.000000,4.000000,2026.000000
max,2026-12-31 00:00:00,70.000000,8.000000,25111.000000,40.000000,31801.000000,138712.000000,129002.160000,106431.410000,43969.990000,7.000000,5.000000,2026.000000
std,NaN,16.612455,1.367664,4659.141600,8.127118,2786.833574,16881.930904,14853.930750,10365.378680,4874.749195,2.221411,1.413376,0.797333

In [16]:
(df["Sales_Amount"] < 0).sum()

np.int64(0)

In [17]:
(df["Quantity"] <= 0).sum()

np.int64(0)

In [18]:
(df["Profit"] < 0).sum()

np.int64(0)

Negative profit may be valid because some sales can be loss-making.

In [19]:
df["Discount_Percent"].describe()

count    30000.000000
mean        12.724400
std          8.127118
min          0.000000
25%          6.000000
50%         13.000000
75%         19.000000
max         40.000000
Name: Discount_Percent, dtype: float64

Check whether values fall within expected business limits (for example, 0–100%).

In [20]:
df["Order_Date"].min()

Timestamp('2024-01-01 00:00:00')

In [21]:
df["Order_Date"].max()

Timestamp('2026-12-31 00:00:00')

Order dates span from January 2024 to December 2025 ...confirming the expected reporting period

In [23]:
#Unique Values

df["Product_Category"].unique()

array(['Fitness', 'Swimming', 'Cycling', 'Camping', 'Yoga', 'Badminton',
       'Cricket', 'Trekking', 'Running', 'Football'], dtype=object)

In [24]:
df["State"].unique()

array(['Gujarat', 'Chandigarh', 'West Bengal', 'Rajasthan', 'Karnataka',
       'Delhi', 'Maharashtra', 'Haryana', 'Telangana', 'Tamil Nadu',
       'Uttar Pradesh'], dtype=object)

In [25]:
df.nunique()

Order_ID              30000
Order_Date             1096
Order_Time             9121
Customer_ID            8998
Customer_Name           120
Gender                    2
Age                      58
Age_Group                 3
City                     12
State                    11
Membership_Type           3
Customer_Segment          3
Product_ID               10
Product_Name             10
Product_Category         10
Brand                     1
Sport_Type               10
Quantity                  8
Unit_Price             9350
Discount_Percent         41
Discount_Amount       13720
Sales_Amount          12014
Final_Amount          15647
Cost_Price            29472
Profit                28917
Store_ID                  5
Store_Name                5
Sales_Channel             3
Payment_Method            4
Salesperson             120
Delivery_Type             2
Delivery_Days             8
Customer_Rating           5
Return_Status             2
Return_Reason             6
Promotion_Campaign        7
Quarter                   4
Month                    12
Year                      3
dtype: int64

**Feature Engineering**

In [26]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Time', 'Customer_ID', 'Customer_Name',
       'Gender', 'Age', 'Age_Group', 'City', 'State', 'Membership_Type',
       'Customer_Segment', 'Product_ID', 'Product_Name', 'Product_Category',
       'Brand', 'Sport_Type', 'Quantity', 'Unit_Price', 'Discount_Percent',
       'Discount_Amount', 'Sales_Amount', 'Final_Amount', 'Cost_Price',
       'Profit', 'Store_ID', 'Store_Name', 'Sales_Channel', 'Payment_Method',
       'Salesperson', 'Delivery_Type', 'Delivery_Days', 'Customer_Rating',
       'Return_Status', 'Return_Reason', 'Promotion_Campaign', 'Quarter',
       'Month', 'Year'],
      dtype='object')

In [36]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [45]:
#Create Order Month
df["Order_Month"] = df["Order_Date"].dt.month_name()

In [46]:
#Create Order Year
df["Order_Year"] = df["Order_Date"].dt.year

In [ ]:
#Create Quarter
df["Quarter"] = df["Order_Date"].dt.quarter

In [ ]:
#Create Day Name
df["Day_Name"] = df["Order_Date"].dt.day_name()

In [50]:
#Create Profit Margin %
df["Profit_Margin"] = (df["Profit"] /df["Final_Amount"]) * 100

for Profitability Analysis

In [53]:
#Create Order Value Category

df["Order_Value"] = pd.cut(
    df["Final_Amount"],
    bins=[0,1000,5000,10000,100000],
    labels=[
        "Low",
        "Medium",
        "High",
        "Premium"
    ]
)

for Customer Segmentation

In [56]:
#Create Age Group

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0,18,25,35,45,60,100],
    labels=[
        "<18",
        "18-25",
        "26-35",
        "36-45",
        "46-60",
        "60+"
    ]
)

In [57]:
#Create High Value Customer

threshold = df["Final_Amount"].quantile(0.75)

df["High_Value_Customer"] = np.where(
    df["Final_Amount"] >= threshold,
    "Yes",
    "No"
)

In [58]:
#Now Save Dataset
df.to_csv("Decathlon_Feature_Engineered.csv",index=False)